# Generated by Django 4.2 on 2023-04-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('evaluator', 'Evaluator'), ('seller', 'Seller')], default='seller', max_length=20),
        ),
    ]
